version: "3.9"

services:
    postgresql_db:
        image: postgres:latest
        container_name: postgresql_db
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin1234
            - POSTGRES_DB=productDb
        ports: 
            - "5432:5432"
        networks:
            - postgres-db-network
        volumes: 
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount local file init.sql to execute on startup
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment: 
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        ports:
            - '5050:80'
        networks:
            - postgres-db-network

networks:
    postgres-db-network:
        driver: bridge